{% set name = "sunode" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 10
  script: "{{ PYTHON }} -m pip install . -vv"

  skip: True  # [py<3.7]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy >=1.19
    - liblapack
    - cffi
    - sundials >=5.3,<6.0
  run:
    - python
    - numpy >=1.19
    - cffi
    - xarray
    - scipy
    - sundials >=5.3,<6.0
    - numba >=0.49
    - typing_extensions
    - sympy >=1.8

test:
  imports:
    - sunode
  requires:
    - pytest
    - hypothesis
    - statsmodels
    - pytensor
  commands:
    - pytest --pyargs sunode

about:
  home: https://github.com/aseyboldt/sunode
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A wrapper around sundials cvodes
